---
- name: configure docker
  hosts: localhost
  become: true  # Asegura que se usen privilegios de sudo
  tasks:
    - name: update and upgrade
      shell: apt-get update && apt-get upgrade -y  # Usamos apt-get en lugar de apt
      become: true  # Asegura que esta tarea use sudo
    
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: true  # Asegura que esta tarea use sudo

    - name: Get Ubuntu release codename from /etc/os-release
      shell: ". /etc/os-release && echo $UBUNTU_CODENAME"  # Usamos el punto (.) en lugar de source
      register: ubuntu_codename
      become: true  # Asegura que esta tarea use sudo

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true  # Asegura que esta tarea use sudo

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
        state: present
      become: true  # Asegura que esta tarea use sudo

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      become: true  # Asegura que esta tarea use sudo

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      become: true  # Asegura que esta tarea use sudo

    - name: Add user to Docker group
      user:
        name: ubuntu
        group: docker
        append: yes
      become: true  # Asegura que esta tarea use sudo

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: true  # Asegura que esta tarea use sudo
