name: install cloud-watch-logs

on:
#  workflow_run:
#    workflows: ["create lmabda-sqs-sns"]
#    types:
#      - completed

jobs:
  building_ec2_and_publish_api:
    runs-on: ubuntu-latest
    steps:

        - name: checkout code 
          uses: actions/checkout@v2
        
        -  name: Set up AWS CLI
           uses: aws-actions/configure-aws-credentials@v1
           with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        
        - name: Obtener dirección IP pública
          run: |
                export PUBLIC_IP=$(aws ec2 describe-instances --region $AWS_REGION --filters "Name=tag:Name,Values=server_prueba_dflatam" \
                --query "Reservations[].Instances[].PublicIpAddress" --output text)
                echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

        

