name: repository_scan
on: 
 push:
    branches:
      - main

jobs:
  scan-all-project-with-snyk:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: install snyk
          run: npm install -g snyk
        
        - name: Authenticate Snyk CLI
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
          run: snyk auth $SNYK_TOKEN
        
        - name: scan IAC ecr buil 
          run: snyk iac  test terraform/** --severity-threshold=high
        

