name: create lmabda-sqs-sns

on:
  workflow_run:
    workflows: ["publish ec2 with api"]
    types:
      - completed

jobs:
  building_ec2_and_publish_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Building ecr repository
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd terraform/lambda_sqs_sns
          terraform init
          terraform refresh
          terraform apply -auto-approve
